version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend
      - FLASK_SERVER_PORT=9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: flask
    environment:
      - MONGO_SERVER_PORT=27107
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    command: mongo-express --admin --url mongodb://mongo:27017
    environment:
      - ME_CONFIG_SITE_BASEURL=/
